# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

sudo: required

services:
  - docker

notifications:
  email: false
  webhooks:
    urls:
      # TODO: generate and encrypt creds. for this repo. using Travis
      # travis2slack webhook to enable DMs on openwhisk-team.slack.com to PR authors with TravisCI results
      # secure: "gfROHzycfSxU85pp/jscreWed1bABKlBa1w+fBH40mZDIYI9Dhgbnq1lqpkBLz51RasPsCmKvZP8j3gm5NunRJWwPeMk0ZmwPuBzVCiOdEr7r/SOr4hQM6CJjLuQWVg8gIR1ZeIQhIc+oHc8KGPDBJdSPo9b89QNCyVXNL47/M9KAKUn2ilwTdHaezlwGnT3yiTvhvYEQhwaXLxHHIfCtlQjPg+d8Ch93xYRCvqfKu4g3owr1bbZZE5AERH7dkKzq5HtzYAxr3M1UZLfSwiQfktnq4cGWrw9XxXCmENTm6HDKCLc7pcOvLZF5NqpItRd4Od1kma5lPKfR1qK8+SjyohpWqakhrJlnBe5x68zXyyq4Y48yuNuGXqVkdQ1faUF1gY0cE6KvsfFLYUvRXUmPZNYYd1xMaouUM6fiVRSyM/liuR8zK750umNRdgNNTlmYXQNJwg/YlF155hqIblf7Idf2Sg6AW5d7mUIvWa1VIemZpvxFb2wG0SUyADhNvTWFLpxmlIP9ddCzz+ZY5CWpe5ZYj2/snXp983fHgAoVEnxc4ifIlaUf1ALcK/BVGzJh5dgpD4JmyDK8C1YoP5hiMRtvbAetxYK9R8YNZs8Q3K2yZvdFgWrNQhW0OiDG5pIOPhg3vx8Syr886YSlYW+kp7QI3d18HFvCo3ZIZb/Qus="

before_install:
- "./tools/travis/cloneutils.sh"

script:
- echo $TRAVIS
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_SECURE_ENV_VARS
- printenv
- "./tools/travis/script.sh"
